CREATE PROCEDURE GetActiveSecond()
BEGIN
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT *
	FROM secondTable
	WHERE Active = true;
    
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;  
END