CREATE PROCEDURE GetActiveFirst()
BEGIN
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT *
	FROM firstTable
	WHERE Active = true;
    
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;  
END
