name: ServicesTestFramework $(Major).$(Minor)$(Rev:.r) Test

trigger:
  batch: true
  branches:
    include:
    - dev
      - main
  paths:
    include:
      - '*'
    exclude:
      - '**/*.md'

parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
    - Release
    - Debug

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildProjectPath: '**/*.csproj'
  testProjectsFilter: '$(System.DefaultWorkingDirectory)/tests/*.Tests/*.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: $(buildProjectPath)

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: $(testProjectsFilter)
      arguments: '--configuration ${{ parameters.buildConfiguration }}'
