CREATE TABLE IF NOT EXISTS hotfixTable (
  Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SomeImportantValue VARCHAR(60) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS extraTAble (
  Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  NothingImportantHere INT(10) DEFAULT NULL,
  PRIMARY KEY (Id)
);

