CREATE TABLE IF NOT EXISTS firstTable (
  Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(60) NOT NULL,
  SomeDate DATETIME DEFAULT NULL,
  Active BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

ALTER TABLE firstTable 
  ADD INDEX idx_firstTable_Name(Name);