CREATE TABLE IF NOT EXISTS secondTable (
  Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SomeText VARCHAR(100) DEFAULT NULL,
  SomeInt INT(10) UNSIGNED DEFAULT NULL,
  Active BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;
